# Generated by Django 3.2.7 on 2021-09-26 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircrafts',
            fields=[
                ('aircraft_code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('model', models.TextField()),
                ('range', models.IntegerField()),
            ],
            options={
                'db_table': 'aircrafts',
            },
        ),
        migrations.CreateModel(
            name='Airports',
            fields=[
                ('airport_code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('airport_name', models.TextField()),
                ('city', models.TextField()),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('timezone', models.TextField()),
            ],
            options={
                'db_table': 'airports',
            },
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('book_ref', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('book_date', models.DateTimeField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'bookings',
            },
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('ticket_no', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('passenger_id', models.CharField(max_length=20)),
                ('passenger_name', models.TextField()),
                ('contact_data', models.JSONField(blank=True, null=True)),
                ('book_ref', models.ForeignKey(db_column='book_ref', on_delete=django.db.models.deletion.CASCADE, to='carriers.bookings')),
            ],
            options={
                'db_table': 'tickets',
            },
        ),
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('flight_id', models.AutoField(primary_key=True, serialize=False)),
                ('flight_no', models.CharField(max_length=6)),
                ('scheduled_departure', models.DateTimeField()),
                ('scheduled_arrival', models.DateTimeField()),
                ('status', models.CharField(max_length=20)),
                ('actual_departure', models.DateTimeField(blank=True, null=True)),
                ('actual_arrival', models.DateTimeField(blank=True, null=True)),
                ('aircraft_code', models.ForeignKey(db_column='aircraft_code', on_delete=django.db.models.deletion.CASCADE, to='carriers.aircrafts')),
                ('arrival_airport', models.ForeignKey(db_column='arrival_airport', on_delete=django.db.models.deletion.CASCADE, related_name='arrival_airport', to='carriers.airports')),
                ('departure_airport', models.ForeignKey(db_column='departure_airport', on_delete=django.db.models.deletion.CASCADE, related_name='departure_airport', to='carriers.airports')),
            ],
            options={
                'db_table': 'flights',
                'unique_together': {('flight_no', 'scheduled_departure')},
            },
        ),
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('aircraft_code', models.OneToOneField(db_column='aircraft_code', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='carriers.aircrafts')),
                ('seat_no', models.CharField(max_length=4)),
                ('fare_conditions', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'seats',
                'unique_together': {('aircraft_code', 'seat_no')},
            },
        ),
        migrations.CreateModel(
            name='TicketFlights',
            fields=[
                ('ticket_no', models.OneToOneField(db_column='ticket_no', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='carriers.tickets')),
                ('fare_conditions', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carriers.flights')),
            ],
            options={
                'db_table': 'ticket_flights',
                'unique_together': {('ticket_no', 'flight')},
            },
        ),
        migrations.CreateModel(
            name='BoardingPasses',
            fields=[
                ('ticket_no', models.OneToOneField(db_column='ticket_no', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='carriers.ticketflights')),
                ('flight_id', models.IntegerField()),
                ('boarding_no', models.IntegerField()),
                ('seat_no', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'boarding_passes',
                'unique_together': {('flight_id', 'seat_no'), ('flight_id', 'boarding_no'), ('ticket_no', 'flight_id')},
            },
        ),
    ]
